from __future__ import annotations

from html import escape

from .models import ExamPack


def render_pack_markdown(pack: ExamPack) -> str:
    lines = [
        f"# {pack.title}",
        "",
        f"**Subject:** {pack.subject}",
        f"**Level:** {pack.level}",
        "",
        pack.summary,
        "",
        "## Skills Practised",
        "",
        *[f"- {skill}" for skill in pack.skills],
        "",
        "## Questions",
        "",
    ]

    for index, item in enumerate(pack.items, start=1):
        lines.extend([f"### Question {index}", "", item.prompt, ""])

    lines.extend(
        [
            "---",
            "",
            "Generated by Exam Materials Studio.",
            "",
        ]
    )
    return "\n".join(lines)


def render_answer_key_markdown(pack: ExamPack) -> str:
    lines = [
        f"# {pack.title} Answer Key",
        "",
        f"**Subject:** {pack.subject}",
        f"**Level:** {pack.level}",
        "",
    ]

    for index, item in enumerate(pack.items, start=1):
        lines.extend([f"## Answer {index}", "", item.answer, ""])
        if item.explanation:
            lines.extend(["**Explanation:**", "", item.explanation, ""])

    return "\n".join(lines)


def render_catalog_html(packs: list[ExamPack]) -> str:
    cards = []
    for pack in packs:
        skills = ", ".join(pack.skills)
        cards.append(
            "\n".join(
                [
                    '<article class="pack-card">',
                    f"  <h2>{escape(pack.title)}</h2>",
                    f"  <p>{escape(pack.summary)}</p>",
                    f"  <p><strong>Subject:</strong> {escape(pack.subject)}</p>",
                    f"  <p><strong>Level:</strong> {escape(pack.level)}</p>",
                    f"  <p><strong>Skills:</strong> {escape(skills)}</p>",
                    f'  <a href="{escape(pack.slug)}.md">Worksheet</a>',
                    f'  <a href="{escape(pack.slug)}-answer-key.md">Answer key</a>',
                    "</article>",
                ]
            )
        )

    body = "\n".join(cards)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Exam Materials Catalog</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; max-width: 960px; }}
    .pack-card {{ border: 1px solid #d0d7de; border-radius: 8px; padding: 1rem; margin: 1rem 0; }}
    a {{ display: inline-block; margin-right: 1rem; }}
  </style>
</head>
<body>
  <h1>Exam Materials Catalog</h1>
  {body}
</body>
</html>
"""

