from __future__ import annotations

import json
from html import escape

from .models import DIFFICULTY_ORDER, ExamPack, PackItem


def render_pack_markdown(pack: ExamPack) -> str:
    lines = [
        f"# {pack.title}",
        "",
        f"**Resource type:** {pack.resource_type}",
        f"**Subject:** {pack.subject}",
        f"**Level:** {pack.level}",
        *[f"**{label}:** {value}" for label, value in _metadata_fields(pack)],
        "",
        pack.summary,
        "",
        *_prerequisites_markdown(pack),
        *_materials_markdown(pack),
        *_curriculum_references_markdown(pack),
        *_learning_objectives_markdown(pack),
        "## Skills Practised",
        "",
        *[f"- {skill}" for skill in pack.skills],
        "",
        "## Questions",
        "",
    ]

    for index, item in enumerate(pack.items, start=1):
        heading = item.item_type.replace("-", " ").title()
        lines.extend([f"### {heading} {index}", "", *_difficulty_markdown(item), item.prompt, ""])

    lines.extend(
        [
            "---",
            "",
            "Generated by Exam Materials Studio.",
            "",
        ]
    )
    return "\n".join(lines)


def render_answer_key_markdown(pack: ExamPack) -> str:
    lines = [
        f"# {pack.title} Answer Key",
        "",
        f"**Resource type:** {pack.resource_type}",
        f"**Subject:** {pack.subject}",
        f"**Level:** {pack.level}",
        *[f"**{label}:** {value}" for label, value in _metadata_fields(pack)],
        "",
        *_prerequisites_markdown(pack),
        *_materials_markdown(pack),
    ]

    for index, item in enumerate(pack.items, start=1):
        lines.extend([f"## Answer {index}", "", *_difficulty_markdown(item), item.answer, ""])
        if item.explanation:
            lines.extend(["**Explanation:**", "", item.explanation, ""])

    return "\n".join(lines)


def render_pack_html(pack: ExamPack) -> str:
    item_cards = []
    for index, item in enumerate(pack.items, start=1):
        heading = item.item_type.replace("-", " ").title()
        item_cards.append(
            "\n".join(
                [
                    "<section>",
                    f"  <h2>{escape(heading)} {index}</h2>",
                    *_difficulty_html(item),
                    f"  <p>{escape(item.prompt)}</p>",
                    "</section>",
                ]
            )
        )

    return _html_page(
        title=pack.title,
        body="\n".join(
            [
                _resource_header(pack),
                *_prerequisites_html(pack),
                *_materials_html(pack),
                *_curriculum_references_html(pack),
                *_learning_objectives_html(pack),
                "<h2>Skills Practised</h2>",
                "<ul>",
                *[f"  <li>{escape(skill)}</li>" for skill in pack.skills],
                "</ul>",
                "<h2>Activities</h2>",
                "\n".join(item_cards),
            ]
        ),
    )


def render_answer_key_html(pack: ExamPack) -> str:
    answer_cards = []
    for index, item in enumerate(pack.items, start=1):
        answer_cards.append(
            "\n".join(_answer_key_section(index, item))
        )

    return _html_page(
        title=f"{pack.title} Answer Key",
        body="\n".join([_resource_header(pack), *_prerequisites_html(pack), *_materials_html(pack), "\n".join(answer_cards)]),
    )


def render_catalog_markdown(packs: list[ExamPack]) -> str:
    lines = ["# Exam Materials Catalog", ""]
    for pack in packs:
        skills = ", ".join(pack.skills)
        metadata = " / ".join(
            value for value in [pack.education_system, pack.exam_board, pack.course] if value
        )
        lines.extend(
            [
                f"## {pack.title}",
                "",
                pack.summary,
                "",
                f"**Type:** {pack.resource_type}",
                f"**Subject:** {pack.subject}",
                f"**Level:** {pack.level}",
            ]
        )
        if metadata:
            lines.append(f"**Track:** {metadata}")
        if pack.duration_minutes:
            lines.append(f"**Estimated time:** {pack.duration_minutes} minutes")
        if pack.prerequisites:
            lines.append(f"**Prerequisites:** {', '.join(pack.prerequisites)}")
        if pack.materials:
            lines.append(f"**Materials:** {', '.join(pack.materials)}")
        if pack.delivery_modes:
            lines.append(f"**Delivery modes:** {', '.join(pack.delivery_modes)}")
        lines.extend(
            [
                f"**Skills:** {skills}",
                "",
                f"- [Resource]({pack.slug}.md)",
                f"- [Answer key]({pack.slug}-answer-key.md)",
                "",
            ]
        )

    return "\n".join(lines)


def render_catalog_json(packs: list[ExamPack], formats: set[str] | None = None) -> str:
    formats = formats or {"markdown", "html"}
    data = {
        "schema_version": 1,
        "resource_count": len(packs),
        "resources": [_catalog_resource(pack, formats) for pack in packs],
    }
    return json.dumps(data, indent=2) + "\n"


def _catalog_resource(pack: ExamPack, formats: set[str]) -> dict[str, object]:
    files: dict[str, str] = {}
    if "markdown" in formats:
        files["markdown"] = f"{pack.slug}.md"
        files["answer_key_markdown"] = f"{pack.slug}-answer-key.md"
    if "html" in formats:
        files["html"] = f"{pack.slug}.html"
        files["answer_key_html"] = f"{pack.slug}-answer-key.html"

    return {
        "title": pack.title,
        "slug": pack.slug,
        "subject": pack.subject,
        "level": pack.level,
        "resource_type": pack.resource_type,
        "education_system": pack.education_system,
        "exam_board": pack.exam_board,
        "course": pack.course,
        "summary": pack.summary,
        "skills": list(pack.skills),
        "learning_objectives": list(pack.learning_objectives),
        "curriculum_references": list(pack.curriculum_references),
        "duration_minutes": pack.duration_minutes,
        "prerequisites": list(pack.prerequisites),
        "materials": list(pack.materials),
        "delivery_modes": list(pack.delivery_modes),
        "item_count": len(pack.items),
        "difficulty_counts": _difficulty_counts(pack),
        "files": files,
    }


def _answer_key_section(index: int, item: PackItem) -> list[str]:
    lines = [
        "<section>",
        f"  <h2>Answer {index}</h2>",
        *_difficulty_html(item),
        f"  <p>{escape(item.answer)}</p>",
    ]
    if item.explanation:
        lines.append(f"  <p><strong>Explanation:</strong> {escape(item.explanation)}</p>")
    lines.append("</section>")
    return lines


def render_catalog_html(packs: list[ExamPack], formats: set[str] | None = None) -> str:
    formats = formats or {"markdown", "html"}
    cards = []
    for pack in packs:
        skills = ", ".join(pack.skills)
        metadata = " / ".join(
            value for value in [pack.education_system, pack.exam_board, pack.course] if value
        )
        links = []
        if "markdown" in formats:
            links.extend(
                [
                    f'  <a href="{escape(pack.slug)}.md">Resource</a>',
                    f'  <a href="{escape(pack.slug)}-answer-key.md">Answer key</a>',
                ]
            )
        if "html" in formats:
            links.extend(
                [
                    f'  <a href="{escape(pack.slug)}.html">HTML</a>',
                    f'  <a href="{escape(pack.slug)}-answer-key.html">Answer key HTML</a>',
                ]
            )
        cards.append(
            "\n".join(
                [
                    '<article class="pack-card">',
                    f"  <h2>{escape(pack.title)}</h2>",
                    f"  <p>{escape(pack.summary)}</p>",
                    f"  <p><strong>Type:</strong> {escape(pack.resource_type)}</p>",
                    f"  <p><strong>Subject:</strong> {escape(pack.subject)}</p>",
                    f"  <p><strong>Level:</strong> {escape(pack.level)}</p>",
                    *([f"  <p><strong>Track:</strong> {escape(metadata)}</p>"] if metadata else []),
                    *(
                        [f"  <p><strong>Estimated time:</strong> {pack.duration_minutes} minutes</p>"]
                        if pack.duration_minutes
                        else []
                    ),
                    *(
                        [f"  <p><strong>Prerequisites:</strong> {escape(', '.join(pack.prerequisites))}</p>"]
                        if pack.prerequisites
                        else []
                    ),
                    *(
                        [f"  <p><strong>Materials:</strong> {escape(', '.join(pack.materials))}</p>"]
                        if pack.materials
                        else []
                    ),
                    *(
                        [f"  <p><strong>Delivery modes:</strong> {escape(', '.join(pack.delivery_modes))}</p>"]
                        if pack.delivery_modes
                        else []
                    ),
                    f"  <p><strong>Skills:</strong> {escape(skills)}</p>",
                    *links,
                    "</article>",
                ]
            )
        )

    body = "\n".join(cards)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Exam Materials Catalog</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; max-width: 960px; }}
    .pack-card {{ border: 1px solid #d0d7de; border-radius: 8px; padding: 1rem; margin: 1rem 0; }}
    a {{ display: inline-block; margin-right: 1rem; }}
  </style>
</head>
<body>
  <h1>Exam Materials Catalog</h1>
  {body}
</body>
</html>
"""


def _metadata_fields(pack: ExamPack) -> list[tuple[str, str]]:
    return [
        (label, value)
        for label, value in [
            ("Education system", pack.education_system),
            ("Exam board", pack.exam_board),
            ("Course", pack.course),
            (
                "Estimated time",
                f"{pack.duration_minutes} minutes" if pack.duration_minutes else "",
            ),
            (
                "Delivery modes",
                ", ".join(pack.delivery_modes) if pack.delivery_modes else "",
            ),
        ]
        if value
    ]


def _learning_objectives_markdown(pack: ExamPack) -> list[str]:
    if not pack.learning_objectives:
        return []
    return [
        "## Learning Objectives",
        "",
        *[f"- {objective}" for objective in pack.learning_objectives],
        "",
    ]


def _prerequisites_markdown(pack: ExamPack) -> list[str]:
    if not pack.prerequisites:
        return []
    return [
        "## Prerequisites",
        "",
        *[f"- {prerequisite}" for prerequisite in pack.prerequisites],
        "",
    ]


def _materials_markdown(pack: ExamPack) -> list[str]:
    if not pack.materials:
        return []
    return [
        "## Materials",
        "",
        *[f"- {material}" for material in pack.materials],
        "",
    ]


def _curriculum_references_markdown(pack: ExamPack) -> list[str]:
    if not pack.curriculum_references:
        return []
    return [
        "## Curriculum References",
        "",
        *[f"- {reference}" for reference in pack.curriculum_references],
        "",
    ]


def _learning_objectives_html(pack: ExamPack) -> list[str]:
    if not pack.learning_objectives:
        return []
    return [
        "<h2>Learning Objectives</h2>",
        "<ul>",
        *[f"  <li>{escape(objective)}</li>" for objective in pack.learning_objectives],
        "</ul>",
    ]


def _prerequisites_html(pack: ExamPack) -> list[str]:
    if not pack.prerequisites:
        return []
    return [
        "<h2>Prerequisites</h2>",
        "<ul>",
        *[f"  <li>{escape(prerequisite)}</li>" for prerequisite in pack.prerequisites],
        "</ul>",
    ]


def _materials_html(pack: ExamPack) -> list[str]:
    if not pack.materials:
        return []
    return [
        "<h2>Materials</h2>",
        "<ul>",
        *[f"  <li>{escape(material)}</li>" for material in pack.materials],
        "</ul>",
    ]


def _curriculum_references_html(pack: ExamPack) -> list[str]:
    if not pack.curriculum_references:
        return []
    return [
        "<h2>Curriculum References</h2>",
        "<ul>",
        *[f"  <li>{escape(reference)}</li>" for reference in pack.curriculum_references],
        "</ul>",
    ]


def _resource_header(pack: ExamPack) -> str:
    metadata = "\n".join(
        [
            f"<p><strong>Resource type:</strong> {escape(pack.resource_type)}</p>",
            f"<p><strong>Subject:</strong> {escape(pack.subject)}</p>",
            f"<p><strong>Level:</strong> {escape(pack.level)}</p>",
            *[f"<p><strong>{escape(label)}:</strong> {escape(value)}</p>" for label, value in _metadata_fields(pack)],
            f"<p>{escape(pack.summary)}</p>",
        ]
    )
    return f"<header>\n<h1>{escape(pack.title)}</h1>\n{metadata}\n</header>"


def _difficulty_markdown(item: PackItem) -> list[str]:
    if not item.difficulty:
        return []
    return [f"**Difficulty:** {item.difficulty}", ""]


def _difficulty_html(item: PackItem) -> list[str]:
    if not item.difficulty:
        return []
    return [f"  <p><strong>Difficulty:</strong> {escape(item.difficulty)}</p>"]


def _difficulty_counts(pack: ExamPack) -> dict[str, int]:
    counts = {
        difficulty: sum(1 for item in pack.items if item.difficulty == difficulty)
        for difficulty in DIFFICULTY_ORDER
    }
    return {difficulty: count for difficulty, count in counts.items() if count}


def _html_page(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; line-height: 1.5; margin: 2rem; max-width: 840px; }}
    header, section {{ border-bottom: 1px solid #d0d7de; padding-bottom: 1rem; margin-bottom: 1rem; }}
    h1, h2 {{ line-height: 1.2; }}
  </style>
</head>
<body>
{body}
</body>
</html>
"""
